In [23]:
import json
import argparse
import os
import datetime
from tqdm import tqdm
import regex as re
from torchvision.ops import box_iou
import torch
def save_json(file_path, data):
    """
    Save data to a JSON file.

    Args:
        file_path (str): Path to the JSON file.
        data (dict): Data to save.
    """
    with open(file_path, 'w') as f:
        json.dump(data, f, indent=4)

def load_json(file_path):
    """
    Load data from a JSON file.

    Args:
        file_path (str): Path to the JSON file.

    Returns:
        dict: Data loaded from the file.
    """
    with open(file_path, 'r') as f:
        return json.load(f)
    
def sort_list_of_dicts(data, key, reverse=False):
    """
    Sort a list of dictionaries by the specified key.

    Args:
        data (list): List of dictionaries to sort.
        key (str): Key to sort by.
        reverse (bool): Sort in descending order if True, ascending if False.

    Returns:
        list: Sorted list of dictionaries.
    """
    return sorted(data, key=lambda x: x[key], reverse=reverse)


def calculate_score(correct_data, generated_data,args,current_date):
    total_data_num = len(correct_data)
    anomaly_data_num = 0
    normal_data_num = 0

    model_predict_anomaly_data_num = 0
    model_predict_normal_data_num = 0

    matched_data_num = 0
    anomaly_matched_data_num = 0



    for i in tqdm(range(total_data_num)):
        assert correct_data[i]["id"] == generated_data[i]["id"], f"ID mismatch at index {i}."
        if correct_data[i]["conversations"][-1]["value"] == "None":
            normal_data_num += 1
        else:
            anomaly_data_num += 1
        
        if generated_data[i]["conversations"][-1]["value"] != "None":
            model_predict_anomaly_data_num += 1
        else:
            model_predict_normal_data_num += 1

        #正常画像の検出判定
        if (correct_data[i]["conversations"][-1]["value"] == "None") and  (generated_data[i]["conversations"][-1]["value"] == "None" or generated_data[i]["conversations"][-1]["value"] == "None."):
            matched_data_num += 1
        # 異常画像の検出判定
        elif (correct_data[i]["conversations"][-1]["value"] != "None") and (generated_data[i]["conversations"][-1]["value"] != "None" and generated_data[i]["conversations"][-1]["value"] != "None."):
            matched_data_num += 1
            anomaly_matched_data_num += 1

    print("-" * 50)
    print(f"Total data number: {total_data_num}")
    print(f"Normal data number: {normal_data_num}")
    print(f"Anomaly data number: {anomaly_data_num}")

    print(f"Model predict normal data number: {model_predict_normal_data_num}")
    print(f"Model predict anomaly data number: {model_predict_anomaly_data_num}")

    print(f"Matched data number: {matched_data_num}")
    print(f"Anomaly matched data number: {anomaly_matched_data_num}")
    print("-" * 50)
    accuracy = matched_data_num / total_data_num
    print(f"Accuracy: {accuracy}")
    precision = anomaly_matched_data_num / model_predict_anomaly_data_num if model_predict_anomaly_data_num > 0 else 0
    print(f"Precision: {precision}")
    recall = anomaly_matched_data_num / anomaly_data_num if anomaly_data_num > 0 else 0
    print(f"Recall: {recall}")
    f1_score = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0
    print(f"F1 Score: {f1_score}")
    print("-" * 50)

    output_data = {
        "filename": args.generated_json,
        "correct_json": args.gt_json,
        "timestamp": current_date,
        "scores": {
            "accuracy": accuracy,
            "precision": precision,
            "recall": recall,
            "f1_score": f1_score
        },
        "data_num": {
            "total_data_num": total_data_num,
            "normal_data_num": normal_data_num,
            "anomaly_data_num": anomaly_data_num,
            "model_predict_normal_data_num": model_predict_normal_data_num,
            "model_predict_anomaly_data_num": model_predict_anomaly_data_num,
            "matched_data_num": matched_data_num,
            "anomaly_matched_data_num": anomaly_matched_data_num
        },
    }
    return output_data

def main(args):
    base_name = os.path.basename(__file__)
    current_date = datetime.datetime.now().strftime('%Y-%m-%dT%H_%M_%S')
    
    
    if args.output_path is None:
        generated_json_folder = os.path.dirname(args.generated_json)
        output_path = os.path.join(generated_json_folder,f"{base_name.split('.')[0]}.json")
    else:
        output_path = args.output_path
    
    print("Loading JSON data...")
    correct_json_path = args.gt_json
    correct_data = load_json(correct_json_path)

    generated_json_path = args.generated_json
    generated_data = load_json(generated_json_path)

    assert len(correct_data) == len(generated_data), "Length of correct and generated data does not match."

    correct_data = sort_list_of_dicts(correct_data, "id")
    generated_data = sort_list_of_dicts(generated_data, "id")

    output_data = calculate_score(correct_data, generated_data,args,current_date)
    
    print(f"Saving sorted JSON data to \"{output_path}\"...")
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
     # Save the output data to the specified output path
    save_json(output_path, output_data)

In [37]:
correct_json_path = "/data_ssd/mvtec_ad/mvtec-test_llava-onevision.json"
correct_data = load_json(correct_json_path)

generated_json_path = "/data_ssd/iam_model/original/llava-onevision-qwen2-7b-ov-hf/eval_output/mvtec-test_llava-onevision/2025-05-26T20_43_50/eval_output.json"
generated_json_path = "/home/omote/omote-data-ssd/iam-llms-finetune/experiment_output/llava-onevision_finetune-llm_guad_5epoch_2025-05-27T10_38_39/eval_output/mvtec-test_llava-onevision/2025-05-28T16_17_46/eval_output.json"
generated_data = load_json(generated_json_path)

assert len(correct_data) == len(generated_data), "Length of correct and generated data does not match."

correct_data = sort_list_of_dicts(correct_data, "id")
generated_data = sort_list_of_dicts(generated_data, "id")


In [38]:
gt_bbox_path = "/data_ssd/mvtec_ad/mvtec_bbox.json"
gt_bbox_data = load_json(gt_bbox_path)
gt_bbox_data = {"/".join(["/dataset"]+k.split("/")[-4:]): v for k, v in gt_bbox_data.items()}

In [39]:
print(len(gt_bbox_data))

1258


In [40]:
print(list(gt_bbox_data.keys())[0])

/dataset/mvtec_test_for_icl/bottle/broken_large/000.png


In [41]:
def extract_bbox_from_text(ans):
    pattern = re.compile(r'\[(((0|1)\.(\d){3}\,\s*){3}((0|1)\.(\d){3}))\]')
    match_list = pattern.findall(ans)

    if len(match_list) > 0:
        answer = [list(map(float,match[0].split(","))) for match in match_list]
    else:
        answer = "FAILED"
    return answer

def calculate_iou(gt_bbox_list, pred_bbox_list):
    iou_matrix = box_iou(torch.tensor(gt_bbox_list).float(), torch.tensor(pred_bbox_list).float())
    iou_argsort_matrix = torch.argsort(iou_matrix.flatten(),descending=True).argsort().reshape(iou_matrix.shape)#iouが大きい順にソートしたインデックスを取得
    # print("-" * 50)
    # print(iou_matrix)
    pred_index_list =  torch.full((len(pred_bbox_list),), False, dtype=torch.bool)
    gt_index_list = torch.full((len(gt_bbox_list),), False, dtype=torch.bool)

    iou_info_list = []

    for i in range(len(gt_bbox_list)):
        max_iou_index = torch.where(iou_argsort_matrix == i)
        if not gt_index_list[max_iou_index[0]] and not pred_index_list[max_iou_index[1]]:
            iou_info_list.append( {
                "gt_index": max_iou_index[0].item(),
                "pred_index": max_iou_index[1].item(),
                "iou_value": iou_matrix[max_iou_index].item()
            })
            gt_index_list[max_iou_index[0]] = True
            pred_index_list[max_iou_index[1]] = True
    # print(iou_info_list)
    return iou_info_list

In [42]:
total_data_num = len(correct_data)
anomaly_data_num = 0
normal_data_num = 0

model_predict_anomaly_data_num = 0
model_predict_normal_data_num = 0

matched_data_num = 0
anomaly_matched_data_num = 0

all_iou_list = []
generated_iou_list = []

gt_iou_num_count= 0

iou_threshold = 0.5

for i in tqdm(range(total_data_num)):
    assert correct_data[i]["id"] == generated_data[i]["id"], f"ID mismatch at index {i}."
    if correct_data[i]["conversations"][-1]["value"] == "None":
        normal_data_num += 1
    else:
        anomaly_data_num += 1
    
    if "None" in generated_data[i]["conversations"][-1]["value"]:
        
        model_predict_normal_data_num += 1
    else:
        model_predict_anomaly_data_num += 1


    #正常画像の検出判定
    if (correct_data[i]["conversations"][-1]["value"] == "None") and  ("None" in generated_data[i]["conversations"][-1]["value"]):
        matched_data_num += 1
    # 異常画像の検出判定
    elif (correct_data[i]["conversations"][-1]["value"] != "None"):
        correct_bbox = gt_bbox_data[correct_data[i]["id"]]
        generated_bbox = extract_bbox_from_text(generated_data[i]["conversations"][-1]["value"])
        gt_iou_num_count += len(correct_bbox)
        # if len(correct_bbox) >  1:
        #     print(correct_data[i]["id"])
        #     print(correct_bbox)
        #     print(generated_bbox)
        if generated_bbox == "FAILED":
            iou_list = [0.0] * len(correct_bbox)
        else:
            iou_list = [item["iou_value"] for item in calculate_iou(correct_bbox, generated_bbox)]
            generated_iou_list.extend(iou_list)
            if len(iou_list) < len(correct_bbox):
                iou_list.extend([0.0] * (len(correct_bbox) - len(iou_list)))

        all_iou_list.extend(iou_list)
        iou_threshold_count = sum(1 for iou in iou_list if iou >= iou_threshold)
        if iou_threshold_count > 0:
            matched_data_num += 1
            anomaly_matched_data_num += 1
            
        # if i > 100:
        #     break
        # matched_data_num += 1
        # anomaly_matched_data_num += 1

assert len(all_iou_list) == gt_iou_num_count, f"Length of all_iou_list {len(all_iou_list)} does not match gt_iou_num_count {len(gt_iou_num_count)}."
print("-" * 50)
print(len(all_iou_list))
print(len(generated_iou_list))

mean_all_iou = sum(all_iou_list) / len(all_iou_list) if len(all_iou_list) > 0 else 0
print(f"Mean IoU: {mean_all_iou}")
mean_generated_iou = sum(generated_iou_list) / len(generated_iou_list) if len(generated_iou_list) > 0 else 0
print(f"Mean Generated IoU: {mean_generated_iou}")

# iou_threshold_count = sum(1 for iou in all_iou_list if iou >= iou_threshold)
# print(f"Number of IoU >= {iou_threshold}: {iou_threshold_count}")

# matched_data_num += iou_threshold_count
# anomaly_matched_data_num = iou_threshold_count if iou_threshold_count > 0 else 0


print("-" * 50)
print(f"Total data number: {total_data_num}")
print(f"Normal data number: {normal_data_num}")
print(f"Anomaly data number: {anomaly_data_num}")

print(f"Model predict normal data number: {model_predict_normal_data_num}")
print(f"Model predict anomaly data number: {model_predict_anomaly_data_num}")

print(f"Matched data number: {matched_data_num}")
print(f"Anomaly matched data number: {anomaly_matched_data_num}")
print("-" * 50)
accuracy = matched_data_num / total_data_num
print(f"Accuracy: {accuracy}")
precision = anomaly_matched_data_num / model_predict_anomaly_data_num if model_predict_anomaly_data_num > 0 else 0
print(f"Precision: {precision}")
recall = anomaly_matched_data_num / anomaly_data_num if anomaly_data_num > 0 else 0
print(f"Recall: {recall}")
f1_score = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0
print(f"F1 Score: {f1_score}")
print("-" * 50)

100%|██████████| 1725/1725 [00:00<00:00, 7695.83it/s]

--------------------------------------------------
1888
730
Mean IoU: 0.12335502769358647
Mean Generated IoU: 0.31903327710341267
--------------------------------------------------
Total data number: 1725
Normal data number: 467
Anomaly data number: 1258
Model predict normal data number: 1005
Model predict anomaly data number: 720
Matched data number: 629
Anomaly matched data number: 168
--------------------------------------------------
Accuracy: 0.3646376811594203
Precision: 0.23333333333333334
Recall: 0.13354531001589826
F1 Score: 0.1698685540950455
--------------------------------------------------


In [ ]:
bbox_1 = [0.0, 0.0, 1.0, 1.0]
bbox_2 = [0.0, 0.0, 0.5, 0.5]
bbox_3 = [0.0, 0.0, 0.75, 0.75]

gt_bbox_list = [bbox_1, bbox_2, bbox_3]
pred_bbox_list = [bbox_2, bbox_3, bbox_1]

iou_matrix = box_iou(torch.tensor(gt_bbox_list).float(), torch.tensor(pred_bbox_list).float())
print("IoU Matrix:")
print(iou_matrix)
iou_argsort_matrix = torch.argsort(iou_matrix.flatten(),descending=True).argsort().reshape(iou_matrix.shape)
print("IoU Argsort Matrix:")
print(iou_argsort_matrix)
print()
print("-" * 50)

pred_index_list =  torch.full((len(pred_bbox_list),), False, dtype=torch.bool)
gt_index_list = torch.full((len(gt_bbox_list),), False, dtype=torch.bool)

iou_info_list = []



for i in range(len(gt_bbox_list)):
    max_iou_index = torch.where(iou_argsort_matrix == i)
    if not gt_index_list[max_iou_index[0]] and not pred_index_list[max_iou_index[1]]:
        iou_info_list.append( {
            "gt_index": max_iou_index[0].item(),
            "pred_index": max_iou_index[1].item(),
            "iou_value": iou_matrix[max_iou_index].item()
        })
        gt_index_list[max_iou_index[0]] = True
        pred_index_list[max_iou_index[1]] = True
    # print(f"Max IoU index for GT bbox {i}: {max_iou_index}")
    # break

print("-" * 50)
print(iou_info_list)

IoU Matrix:
tensor([[0.2500, 0.5625, 1.0000],
        [1.0000, 0.4444, 0.2500]])
IoU Argsort Matrix:
tensor([[4, 2, 0],
        [1, 3, 5]])

--------------------------------------------------
--------------------------------------------------
[{'gt_index': 0, 'pred_index': 2, 'iou_value': 1.0}, {'gt_index': 1, 'pred_index': 0, 'iou_value': 1.0}]


In [12]:
print(iou_matrix.flatten())
print(torch.argsort(iou_matrix.flatten(),descending=True))
print(torch.sort(iou_matrix.flatten(),descending=True))
print(torch.sort(iou_matrix,descending=True).indices)

tensor([0.2500, 0.5625, 1.0000, 1.0000, 0.4444, 0.2500, 0.4444, 1.0000, 0.5625])
tensor([2, 3, 7, 1, 8, 4, 6, 0, 5])
torch.return_types.sort(
values=tensor([1.0000, 1.0000, 1.0000, 0.5625, 0.5625, 0.4444, 0.4444, 0.2500, 0.2500]),
indices=tensor([2, 3, 7, 1, 8, 4, 6, 0, 5]))
tensor([[2, 1, 0],
        [0, 1, 2],
        [1, 2, 0]])


In [ ]:
total_data_num = len(correct_data)
anomaly_data_num = 0
normal_data_num = 0

model_predict_anomaly_data_num = 0
model_predict_normal_data_num = 0

matched_data_num = 0
anomaly_matched_data_num = 0



for i in tqdm(range(total_data_num)):
    assert correct_data[i]["id"] == generated_data[i]["id"], f"ID mismatch at index {i}."
    if correct_data[i]["conversations"][-1]["value"] == "None":
        normal_data_num += 1
    else:
        anomaly_data_num += 1
    
    if generated_data[i]["conversations"][-1]["value"] != "None":
        model_predict_anomaly_data_num += 1
    else:
        model_predict_normal_data_num += 1

    #正常画像の検出判定
    if (correct_data[i]["conversations"][-1]["value"] == "None") and  (generated_data[i]["conversations"][-1]["value"] == "None" or generated_data[i]["conversations"][-1]["value"] == "None."):
        matched_data_num += 1
    # 異常画像の検出判定
    elif (correct_data[i]["conversations"][-1]["value"] != "None") and (generated_data[i]["conversations"][-1]["value"] != "None" and generated_data[i]["conversations"][-1]["value"] != "None."):
        matched_data_num += 1
        anomaly_matched_data_num += 1
        

print("-" * 50)
print(f"Total data number: {total_data_num}")
print(f"Normal data number: {normal_data_num}")
print(f"Anomaly data number: {anomaly_data_num}")

print(f"Model predict normal data number: {model_predict_normal_data_num}")
print(f"Model predict anomaly data number: {model_predict_anomaly_data_num}")

print(f"Matched data number: {matched_data_num}")
print(f"Anomaly matched data number: {anomaly_matched_data_num}")
print("-" * 50)
accuracy = matched_data_num / total_data_num
print(f"Accuracy: {accuracy}")
precision = anomaly_matched_data_num / model_predict_anomaly_data_num if model_predict_anomaly_data_num > 0 else 0
print(f"Precision: {precision}")
recall = anomaly_matched_data_num / anomaly_data_num if anomaly_data_num > 0 else 0
print(f"Recall: {recall}")
f1_score = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0
print(f"F1 Score: {f1_score}")
print("-" * 50)

output_data = {
    "filename": args.generated_json,
    "correct_json": args.gt_json,
    "timestamp": current_date,
    "scores": {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1_score": f1_score
    },
    "data_num": {
        "total_data_num": total_data_num,
        "normal_data_num": normal_data_num,
        "anomaly_data_num": anomaly_data_num,
        "model_predict_normal_data_num": model_predict_normal_data_num,
        "model_predict_anomaly_data_num": model_predict_anomaly_data_num,
        "matched_data_num": matched_data_num,
        "anomaly_matched_data_num": anomaly_matched_data_num
    },
}